# Site settings
title: Like a light in the fog
email: matthieu@brouillard.fr
description: > # this means to ignore newlines until "baseurl:"
  a mainly technical java blog by a java developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.matthieu.brouillard.fr" # the base hostname & protocol for your site
twitter_username: alightinthefog
github_username:  McFoggy

permalink: pretty

include: [".well-known"]

exclude: [vendor]

timezone: Europe/Paris
